//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinTrackForWindows.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinTrackForWindows.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string Account_Name {
            get {
                return ResourceManager.GetString("Account_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account_Type.
        /// </summary>
        internal static string Account_Type {
            get {
                return ResourceManager.GetString("Account_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Accounts_Nav_Title {
            get {
                return ResourceManager.GetString("Accounts_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apperance.
        /// </summary>
        internal static string Apperance {
            get {
                return ResourceManager.GetString("Apperance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget_Name.
        /// </summary>
        internal static string Budget_Name {
            get {
                return ResourceManager.GetString("Budget_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets.
        /// </summary>
        internal static string Budgets_Nav_Title {
            get {
                return ResourceManager.GetString("Budgets_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category_Name.
        /// </summary>
        internal static string Category_Name {
            get {
                return ResourceManager.GetString("Category_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an existing category or type to create a new one..
        /// </summary>
        internal static string Category_ToolTip {
            get {
                return ResourceManager.GetString("Category_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Form.
        /// </summary>
        internal static string Clear_Form {
            get {
                return ResourceManager.GetString("Clear_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to edit.
        /// </summary>
        internal static string Click_To_Edit {
            get {
                return ResourceManager.GetString("Click_To_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currencies_Nav_Title {
            get {
                return ResourceManager.GetString("Currencies_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_Nav_Title {
            get {
                return ResourceManager.GetString("Dashboard_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debts.
        /// </summary>
        internal static string Debts_Nav_Title {
            get {
                return ResourceManager.GetString("Debts_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Name.
        /// </summary>
        internal static string Filter_By_Name {
            get {
                return ResourceManager.GetString("Filter_By_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FinBot.
        /// </summary>
        internal static string FinBot_Nav_Title {
            get {
                return ResourceManager.GetString("FinBot_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Balance.
        /// </summary>
        internal static string Max_Balance {
            get {
                return ResourceManager.GetString("Max_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Balance.
        /// </summary>
        internal static string Min_Balance {
            get {
                return ResourceManager.GetString("Min_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Accounts.
        /// </summary>
        internal static string My_Accounts_Title {
            get {
                return ResourceManager.GetString("My_Accounts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Budgets.
        /// </summary>
        internal static string My_Budgets_Title {
            get {
                return ResourceManager.GetString("My_Budgets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No budget found to display..
        /// </summary>
        internal static string No_Budgets {
            get {
                return ResourceManager.GetString("No_Budgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached Amount.
        /// </summary>
        internal static string Reached_Amount {
            get {
                return ResourceManager.GetString("Reached_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports_Nav_Title {
            get {
                return ResourceManager.GetString("Reports_Nav_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Amount.
        /// </summary>
        internal static string Target_Amount {
            get {
                return ResourceManager.GetString("Target_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction_Type.
        /// </summary>
        internal static string Transaction_Type {
            get {
                return ResourceManager.GetString("Transaction_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions.
        /// </summary>
        internal static string Transactions_Nav_Title {
            get {
                return ResourceManager.GetString("Transactions_Nav_Title", resourceCulture);
            }
        }
    }
}
